### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by baileylo** [baileylo/openpub#40]
Need to support the existing structure of pages.
A `page` is similar to a `post`, except there's no description, categories, and is only HTML. This will be a separate entity for the time being, but we can merge it into `post` later. 
## Schema

``` yaml
Posts 
    columns:
        id: { type: integer }
        body: { type: text }
        title: { type: varcahr }
        slug: { type: varchar}
    indexes:
        slug: {unique: true}
```
## Routes:
- There should be a permalink available from `.com/{slug}`, this should be achieved through a controller that will render any matching post and than any matching page.
- There should be simple crud pages for pages as well
