### ISSUE TITLE
Site Metadata Storage

### ISSUE THREAD

**Issue by baileylo** [baileylo/openpub#67]
Should be implemented using a single table named `site_metadata`.

``` yaml
table: site_metadata
columns:
  id:                  { type: unsigned tinyint, auto_increment: true}
  google_analytics_id: { type: unsigned integer, nullable: true }
  name:                { type: varchar,          nullable: false }
  description:         { type: text,             nullable: false, default: '' }
  last_updated:        { type: DateTime }
  facebook_app_id:     { type: unsigned integer, nullable true }
```
